"""PubMed (NCBI E-utilities) evidence source adapter.

Offline fixture mode is the default and only mode in the demo environment.
Live retrieval is supported when ``offline_only=False`` in the query parameters
and a valid ``PUBMED_API_KEY`` is configured, but is excluded from the automated
test suite (mark live tests with ``pytest.mark.live`` and skip them by default).

Fields captured from each article:
  - PMID, title, abstract, authors, journal, publication date, DOI,
    MeSH terms, publication types, language

Fields NOT inferred or generated by this adapter:
  - citation counts (not available via E-utilities efetch without extra calls)
  - full-text body (abstract only)
  - clinical quality ratings or grading

Partial dates: PubMed records sometimes have month+year but no day, or year only.
The ``date_precision`` field on the normalized record captures this accurately.
"""

from __future__ import annotations

import hashlib
import json
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from src.evidence_sources.base import RawFetchResult
from src.schemas.evidence import EvidenceSourceName, RawEvidenceRecord
from src.schemas.retrieval import RetrievalError, SourceSpecificQuery
from src.utils.exceptions import FixtureManifestError, RetrievalParseError

_SOURCE: EvidenceSourceName = "pubmed"


def _content_hash(payload: dict[str, Any]) -> str:
    raw = json.dumps(payload, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(raw.encode()).hexdigest()[:16]


class PubMedAdapter:
    """Offline-first PubMed adapter that reads from versioned JSON fixtures."""

    source_name: EvidenceSourceName = _SOURCE

    def __init__(self, fixture_dir: Path) -> None:
        self._fixture_dir = Path(fixture_dir)

    # ------------------------------------------------------------------
    # Protocol implementation
    # ------------------------------------------------------------------

    def fetch(self, query: SourceSpecificQuery, run_id: str) -> RawFetchResult:
        """Return raw records from the offline fixture for the given query."""
        manifest_path = self._fixture_dir / "manifest.json"
        if not manifest_path.exists():
            err = RetrievalError(
                source_name=_SOURCE,
                error_type="fixture_missing",
                message=f"PubMed fixture manifest not found: {manifest_path}",
            )
            return RawFetchResult(source_name=_SOURCE, errors=[err])

        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception as exc:
            raise FixtureManifestError(f"Cannot parse PubMed manifest: {exc}") from exc

        manifest_version = manifest.get("version", "unknown")
        fixture_files: list[str] = manifest.get("fixture_files", [])

        records: list[RawEvidenceRecord] = []
        errors: list[RetrievalError] = []

        for fname in fixture_files:
            fpath = self._fixture_dir / fname
            if not fpath.exists():
                errors.append(
                    RetrievalError(
                        source_name=_SOURCE,
                        error_type="fixture_missing",
                        message=f"PubMed fixture file missing: {fname}",
                        is_fatal_for_source=False,
                    )
                )
                continue
            try:
                data = json.loads(fpath.read_text(encoding="utf-8"))
                articles: list[dict[str, Any]] = data if isinstance(data, list) else [data]
                for article in articles:
                    pmid = str(article.get("pmid", ""))
                    if not pmid:
                        continue
                    content_hash = _content_hash(article)
                    records.append(
                        RawEvidenceRecord(
                            id=f"raw-pubmed-{pmid}-{content_hash}",
                            source_name=_SOURCE,
                            retrieval_run_id=run_id,
                            source_identifier=pmid,
                            raw_payload=article,
                            content_hash=content_hash,
                            fetched_at=datetime.now(UTC),
                            is_fixture_data=True,
                            fixture_manifest_version=manifest_version,
                        )
                    )
            except RetrievalParseError:
                raise
            except Exception as exc:
                errors.append(
                    RetrievalError(
                        source_name=_SOURCE,
                        error_type="parse_error",
                        message=f"Failed to parse PubMed fixture '{fname}': {exc}",
                        is_fatal_for_source=False,
                    )
                )

        return RawFetchResult(
            source_name=_SOURCE,
            records=records,
            errors=errors,
            extra_metadata={"manifest_version": manifest_version},
        )

    def ping(self) -> bool:
        return True

    # ------------------------------------------------------------------
    # Live retrieval (excluded from offline test suite)
    # ------------------------------------------------------------------

    def fetch_live(
        self,
        query_string: str,
        run_id: str,
        api_key: str | None = None,
        max_results: int = 50,
    ) -> RawFetchResult:
        """Fetch records from the live NCBI E-utilities API.

        Requires network access + optional API key for higher rate limits.
        Mark tests using this method with ``@pytest.mark.live`` and exclude from
        the default test run with ``pytest -m 'not live'``.
        """
        import httpx

        base = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
        params: dict[str, Any] = {
            "db": "pubmed",
            "term": query_string,
            "retmax": max_results,
            "retmode": "json",
        }
        if api_key:
            params["api_key"] = api_key

        try:
            with httpx.Client(timeout=30) as client:
                search_resp = client.get(f"{base}/esearch.fcgi", params=params)
                search_resp.raise_for_status()
                pmids: list[str] = search_resp.json().get("esearchresult", {}).get("idlist", [])
                if not pmids:
                    return RawFetchResult(source_name=_SOURCE)

                fetch_params: dict[str, Any] = {
                    "db": "pubmed",
                    "id": ",".join(pmids),
                    "retmode": "json",
                    "rettype": "abstract",
                }
                if api_key:
                    fetch_params["api_key"] = api_key
                fetch_resp = client.get(f"{base}/efetch.fcgi", params=fetch_params)
                fetch_resp.raise_for_status()
                raw_json = fetch_resp.json()
        except httpx.TimeoutException as exc:
            raise RetrievalParseError(f"PubMed live fetch timed out: {exc}") from exc
        except Exception as exc:
            raise RetrievalParseError(f"PubMed live fetch failed: {exc}") from exc

        articles_map = raw_json.get("PubmedArticleSet", {}) or raw_json.get("result", {})
        records: list[RawEvidenceRecord] = []
        uid_list = list(articles_map.keys()) if isinstance(articles_map, dict) else []
        for uid in uid_list:
            if uid == "uids":
                continue
            article = articles_map[uid]
            if not isinstance(article, dict):
                continue
            ch = _content_hash(article)
            records.append(
                RawEvidenceRecord(
                    id=f"raw-pubmed-{uid}-{ch}",
                    source_name=_SOURCE,
                    retrieval_run_id=run_id,
                    source_identifier=uid,
                    raw_payload=article,
                    content_hash=ch,
                    fetched_at=datetime.now(UTC),
                    is_fixture_data=False,
                )
            )
        return RawFetchResult(source_name=_SOURCE, records=records)


# Provide a module-level unique ID helper used by normalizer
def _new_evidence_id(prefix: str = "ev-pubmed") -> str:
    return f"{prefix}-{uuid.uuid4().hex[:8]}"
