"""Provider-agnostic LLM client interface.

Supports Anthropic (claude-*), OpenAI (gpt-*), and a deterministic demo mode
that returns pre-computed fixture responses so the application runs without
any API key.

Usage:
    client = get_llm_client()          # auto-selects based on settings
    response = client.complete(messages, task="pico_parse")
"""

import hashlib
import logging
from abc import ABC, abstractmethod
from typing import Any

from pydantic import BaseModel

logger = logging.getLogger(__name__)

# Optional provider imports — application does not fail if packages are absent
try:
    import anthropic as _anthropic

    _ANTHROPIC_AVAILABLE = True
except ImportError:
    _ANTHROPIC_AVAILABLE = False

try:
    import openai as _openai

    _OPENAI_AVAILABLE = True
except ImportError:
    _OPENAI_AVAILABLE = False


class LLMMessage(BaseModel):
    """A single message in an LLM conversation."""

    role: str  # "user" | "assistant" | "system"
    content: str


class LLMResponse(BaseModel):
    """Structured response from any LLM provider or demo mode."""

    content: str = ""
    model: str = "demo"
    is_demo_mode: bool = True
    tokens_used: int | None = None
    prompt_hash: str | None = None
    task: str = "default"


# ── Pre-computed demo responses ────────────────────────────────────────────────

_DEMO_RESPONSES: dict[str, str] = {
    "pico_parse": (
        "[DEMO MODE] PICO extraction for: T2DM + CKD + SGLT2 inhibitors.\n\n"
        "Population: Adults ≥18 years with ICD-10-CM E11.* (Type 2 diabetes mellitus) "
        "AND N18.1–N18.5 (Chronic kidney disease, stages 1–5), enrolled ≥12 months.\n\n"
        "Intervention: SGLT2 inhibitor exposure (empagliflozin, dapagliflozin, canagliflozin) "
        "identified via RxNorm ingredient concepts 1545653, 1488564, 1373458.\n\n"
        "Comparator: None specified (single-arm descriptive cohort characterization).\n\n"
        "Outcomes: eGFR trajectory (LOINC 62238-1), hospitalization for heart failure, "
        "all-cause mortality, acute kidney injury.\n\n"
        "Timeframe: 12-month minimum lookback; configurable follow-up."
    ),
    "phenotype_build": (
        "[DEMO MODE] Candidate phenotype logic for T2DM+CKD SGLT2 cohort.\n\n"
        "Inclusion: ≥1 qualifying T2DM diagnosis (E11.*) within 12-month lookback; "
        "≥1 qualifying CKD diagnosis (N18.1–N18.5) within 12-month lookback; "
        "age ≥18 at index date; ≥1 SGLT2 inhibitor prescription at index date.\n\n"
        "Exclusion: ESRD (N18.6) at or before index date; dialysis or renal transplant "
        "(CPT 90935, 90937, 50360); eGFR <20 mL/min/1.73m² within 30 days before index.\n\n"
        "Note: These are candidate mappings generated in demo mode. All codes require "
        "clinical review before use in a production phenotype."
    ),
    "evidence_brief_intro": (
        "[DEMO MODE] Evidence brief introduction for SGLT2 inhibitors in T2DM+CKD.\n\n"
        "SGLT2 inhibitors represent a class of antidiabetic agents with demonstrated "
        "cardiorenal protective effects in clinical trials. Key evidence includes the "
        "EMPA-REG OUTCOME trial (empagliflozin), CREDENCE trial (canagliflozin), and "
        "DAPA-CKD trial (dapagliflozin), each showing reductions in CKD progression "
        "and cardiovascular events in high-risk populations.\n\n"
        "This brief summarizes publicly available evidence retrieved from PubMed and "
        "ClinicalTrials.gov. All synthetic cohort results are derived from Synthea-generated "
        "data and do not represent real patient outcomes."
    ),
    "default": (
        "[DEMO MODE] This response was generated by the deterministic demo client. "
        "Configure LLM_PROVIDER and an API key in .env to enable live LLM responses."
    ),
}


# ── Abstract base ──────────────────────────────────────────────────────────────


class BaseLLMClient(ABC):
    """Abstract base for all LLM provider clients."""

    @abstractmethod
    def complete(
        self,
        messages: list[LLMMessage],
        task: str = "default",
        max_tokens: int = 1024,
        **kwargs: Any,
    ) -> LLMResponse:
        """Send messages and return a structured response."""
        ...

    @staticmethod
    def _hash_prompt(messages: list[LLMMessage]) -> str:
        text = "||".join(f"{m.role}:{m.content}" for m in messages)
        return hashlib.sha256(text.encode()).hexdigest()[:16]


# ── Demo client ────────────────────────────────────────────────────────────────


class DemoLLMClient(BaseLLMClient):
    """Deterministic demo client that returns pre-computed fixture responses.

    Always available — used when no API key is configured or when DEMO_MODE=true.
    Responses are clearly labeled '[DEMO MODE]' so users are never misled.
    """

    def complete(
        self,
        messages: list[LLMMessage],
        task: str = "default",
        max_tokens: int = 1024,
        **kwargs: Any,
    ) -> LLMResponse:
        content = _DEMO_RESPONSES.get(task, _DEMO_RESPONSES["default"])
        logger.debug("DemoLLMClient: serving pre-computed response for task='%s'", task)
        return LLMResponse(
            content=content,
            model="demo",
            is_demo_mode=True,
            prompt_hash=self._hash_prompt(messages),
            task=task,
        )


# ── Anthropic client ──────────────────────────────────────────────────────────


class AnthropicLLMClient(BaseLLMClient):
    """LLM client backed by the Anthropic Messages API."""

    def __init__(self, api_key: str, model: str = "claude-sonnet-4-6") -> None:
        if not _ANTHROPIC_AVAILABLE:
            raise ImportError(
                "anthropic package not installed. Run: pip install 'anthropic>=0.25.0'"
            )
        self._client = _anthropic.Anthropic(api_key=api_key)
        self.model = model

    def complete(
        self,
        messages: list[LLMMessage],
        task: str = "default",
        max_tokens: int = 1024,
        **kwargs: Any,
    ) -> LLMResponse:
        api_messages = [
            {"role": m.role, "content": m.content} for m in messages if m.role != "system"
        ]
        system = next((m.content for m in messages if m.role == "system"), None)

        response = self._client.messages.create(
            model=self.model,
            max_tokens=max_tokens,
            messages=api_messages,
            **({"system": system} if system else {}),
        )
        content = response.content[0].text if response.content else ""
        tokens = (response.usage.input_tokens or 0) + (response.usage.output_tokens or 0)

        return LLMResponse(
            content=content,
            model=self.model,
            is_demo_mode=False,
            tokens_used=tokens,
            prompt_hash=self._hash_prompt(messages),
            task=task,
        )


# ── OpenAI client ──────────────────────────────────────────────────────────────


class OpenAILLMClient(BaseLLMClient):
    """LLM client backed by the OpenAI Chat Completions API."""

    def __init__(self, api_key: str, model: str = "gpt-4o") -> None:
        if not _OPENAI_AVAILABLE:
            raise ImportError("openai package not installed. Run: pip install 'openai>=1.14.0'")
        self._client = _openai.OpenAI(api_key=api_key)
        self.model = model

    def complete(
        self,
        messages: list[LLMMessage],
        task: str = "default",
        max_tokens: int = 1024,
        **kwargs: Any,
    ) -> LLMResponse:
        api_messages = [{"role": m.role, "content": m.content} for m in messages]

        response = self._client.chat.completions.create(
            model=self.model,
            messages=api_messages,
            max_tokens=max_tokens,
        )
        content = response.choices[0].message.content or ""
        tokens = response.usage.total_tokens if response.usage else None

        return LLMResponse(
            content=content,
            model=self.model,
            is_demo_mode=False,
            tokens_used=tokens,
            prompt_hash=self._hash_prompt(messages),
            task=task,
        )


# ── Factory ────────────────────────────────────────────────────────────────────


def get_llm_client(
    provider: str | None = None,
    api_key: str | None = None,
    model: str | None = None,
) -> BaseLLMClient:
    """Return the appropriate LLM client based on configuration.

    Falls back to DemoLLMClient when no provider is configured or packages
    are unavailable. This ensures the application always works offline.
    """
    from src.config.settings import get_settings

    settings = get_settings()
    resolved_provider = provider or settings.llm_provider
    resolved_model = model or settings.active_llm_model

    if settings.is_demo_mode or not resolved_provider:
        logger.info("LLM client: using DemoLLMClient (demo mode)")
        return DemoLLMClient()

    if resolved_provider == "anthropic":
        key = api_key or settings.anthropic_api_key
        if not key:
            logger.warning(
                "Anthropic provider configured but no API key found; falling back to demo"
            )
            return DemoLLMClient()
        return AnthropicLLMClient(api_key=key, model=resolved_model)

    if resolved_provider == "openai":
        key = api_key or settings.openai_api_key
        if not key:
            logger.warning("OpenAI provider configured but no API key found; falling back to demo")
            return DemoLLMClient()
        return OpenAILLMClient(api_key=key, model=resolved_model)

    logger.warning("Unknown LLM provider '%s'; falling back to demo", resolved_provider)
    return DemoLLMClient()
