"""Evidence Brief — generate and review a structured evidence brief.

Page 6 of the Clinical Question-Evidence Studio.
Gated on: completed evidence retrieval run (Page 5).

IMPORTANT DISCLAIMER: All briefs contain automated output.
No brief generated on this page constitutes a clinical recommendation.
The disclaimer is always visible and cannot be dismissed.
"""

from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

from app.components.ui_helpers import (
    SESSION_KEY_PHENOTYPE,
    SESSION_KEY_QUESTION,
    SESSION_KEY_RETRIEVAL_RUN,
    sidebar_data_note_text,
    sidebar_disclaimer_text,
)

st.set_page_config(
    page_title="Evidence Brief | Clinical Q-E Studio",
    page_icon="📄",
    layout="wide",
)

with st.sidebar:
    st.markdown("---")
    st.warning(sidebar_disclaimer_text())
    st.caption(sidebar_data_note_text())

# ---------------------------------------------------------------------------
# Safety disclaimer — always visible, always first
# ---------------------------------------------------------------------------

st.error(
    "**Required notice:** All content on this page is generated by automated methods. "
    "It is **not a clinical recommendation**, has not been clinically validated, "
    "and must **not** be used for patient care decisions."
)

# ---------------------------------------------------------------------------
# Gate checks
# ---------------------------------------------------------------------------

question = st.session_state.get(SESSION_KEY_QUESTION)
phenotype = st.session_state.get(SESSION_KEY_PHENOTYPE)
retrieval_run = st.session_state.get(SESSION_KEY_RETRIEVAL_RUN)

if question is None or phenotype is None:
    st.warning(
        "An approved clinical question and reviewed phenotype are required. "
        "Complete Pages 2 and 3 first."
    )
    st.stop()

if retrieval_run is None:
    st.warning(
        "A completed evidence retrieval run is required. Complete Page 5 (External Evidence) first."
    )
    st.stop()

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------

st.title("Evidence Brief")
st.markdown(
    f"""
**Question:** {question.question_text}

**Phenotype:** {phenotype.name} (v{phenotype.version})

**Evidence run:** `{retrieval_run.run_id}`
"""
)

# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

st.markdown("---")
st.subheader("Generate Brief")
st.caption(
    "The deterministic mode uses pre-validated templates mapped to the retrieved evidence records. "
    "Live LLM mode requires an API key and is excluded from the default demo. "
    "All outputs are subject to the required disclaimer above."
)

if "generated_brief" not in st.session_state:
    st.session_state["generated_brief"] = None
if "brief_qa" not in st.session_state:
    st.session_state["brief_qa"] = None
if "brief_warnings" not in st.session_state:
    st.session_state["brief_warnings"] = []

col_gen, col_reset = st.columns([2, 1])
with col_gen:
    generate_btn = st.button("Generate Evidence Brief (Deterministic)", type="primary")
with col_reset:
    if st.button("Clear Brief"):
        st.session_state["generated_brief"] = None
        st.session_state["brief_qa"] = None
        st.session_state["brief_warnings"] = []
        st.rerun()

if generate_btn:
    with st.spinner("Running 8-step brief generation pipeline..."):
        try:
            from src.evidence.service import get_evidence_service
            from src.synthesis.brief_service import EvidenceBriefService

            ev_service = get_evidence_service()
            run_data = ev_service.get_run_as_dict(retrieval_run.run_id)

            svc = EvidenceBriefService(
                question_id=getattr(question, "id", "q-sglt2-ckd-cvd"),
                phenotype_id=getattr(phenotype, "id", "pheno-sglt2"),
                phenotype_version=getattr(phenotype, "version", "1.0.0"),
            )
            result = svc.generate(
                run_data=run_data,
                generation_mode="deterministic",
                question_text=question.question_text,
            )
            st.session_state["generated_brief"] = result.brief
            st.session_state["brief_qa"] = result.qa_summary
            st.session_state["brief_warnings"] = result.warnings

            from src.synthesis.repository import get_synthesis_repository

            repo = get_synthesis_repository()
            qa_results = repo.get_brief_qa(result.brief.brief_id)
            st.session_state["brief_qa_results"] = qa_results

        except Exception as exc:
            st.error(f"Brief generation failed: {exc}")
            st.stop()

# ---------------------------------------------------------------------------
# Display brief
# ---------------------------------------------------------------------------

brief = st.session_state.get("generated_brief")
qa_summary = st.session_state.get("brief_qa")

if brief is None:
    st.info("No brief generated yet. Click 'Generate Evidence Brief' above.")
    st.stop()

# Warnings banner
for w in st.session_state.get("brief_warnings", []):
    st.warning(w)

# Disclaimer (repeated from brief object — required)
st.info(f"**Brief disclaimer:** {brief.disclaimer}")

# Metadata row
mcol1, mcol2, mcol3, mcol4 = st.columns(4)
mcol1.metric("Claims", len(brief.claims))
mcol2.metric("Evidence gaps", len(brief.evidence_gaps))
mcol3.metric("Citations", len(brief.bibliography))
mcol4.metric("Review status", brief.human_review_status.replace("_", " ").title())

st.caption(
    f"Brief ID: `{brief.brief_id}` · "
    f"Mode: {brief.generation_mode} · "
    f"Snapshot: `{brief.evidence_snapshot_id}` · "
    f"Content hash: `{brief.content_hash}`"
)

st.markdown("---")

# Data notice
st.caption(f"**Data notice:** {brief.data_notice}")

# Claims by dimension
_DIM_LABELS = {
    "population": "Population",
    "intervention": "Intervention",
    "outcome": "Outcomes",
    "safety": "Safety",
    "design": "Study Design",
    "coverage": "Coverage / Policy",
    "evidence_gap": "Evidence Gap",
}
_CLAIM_ICONS = {
    "supported": "✓",
    "exploratory": "◐",
    "insufficient_evidence": "○",
}

dim_order = [
    "population",
    "intervention",
    "outcome",
    "safety",
    "design",
    "coverage",
    "evidence_gap",
]
grouped: dict[str, list] = {}
for c in brief.claims:
    grouped.setdefault(c.dimension, []).append(c)

for dim in dim_order:
    claims = grouped.get(dim, [])
    if not claims:
        continue
    st.subheader(_DIM_LABELS.get(dim, dim.title()))
    for claim in claims:
        icon = _CLAIM_ICONS.get(claim.claim_type, "•")
        cit_nums = sorted({cit.citation_number for cit in claim.citations})
        cit_str = " ".join(f"[{n}]" for n in cit_nums)
        with st.expander(f"{icon} {claim.text[:80]}...", expanded=True):
            st.markdown(claim.text)
            if cit_str:
                st.caption(f"**Sources:** {cit_str}")
            if claim.design_limitations:
                st.markdown("**Design limitations:**")
                for lim in claim.design_limitations:
                    st.markdown(f"- {lim}")
            if claim.uncertainty_note:
                st.caption(f"*Uncertainty:* {claim.uncertainty_note}")

# Evidence gaps
if brief.evidence_gaps:
    st.markdown("---")
    st.subheader("Evidence Gaps")
    for gap in brief.evidence_gaps:
        with st.expander(f"○ {gap.description[:80]}"):
            st.markdown(gap.description)
            for lim in gap.limitations:
                st.markdown(f"- {lim}")

# Limitations
if brief.limitations:
    st.markdown("---")
    st.subheader("Limitations")
    for lim in brief.limitations:
        st.markdown(f"- {lim}")

# Bibliography
if brief.bibliography:
    st.markdown("---")
    st.subheader("Bibliography")
    for cit in sorted(brief.bibliography, key=lambda c: c.citation_number):
        url_part = f" — [{cit.url}]({cit.url})" if cit.url else ""
        st.markdown(
            f"**[{cit.citation_number}]** {cit.title} "
            f"({cit.source_type}; {cit.source_specific_id}){url_part}"
        )

# ---------------------------------------------------------------------------
# QA Summary
# ---------------------------------------------------------------------------

if qa_summary:
    st.markdown("---")
    st.subheader("QA Summary")
    qcol1, qcol2, qcol3, qcol4 = st.columns(4)
    qcol1.metric("Passed", qa_summary.get("passed", 0))
    qcol2.metric("Failed", qa_summary.get("failed", 0), delta_color="inverse")
    qcol3.metric("Warnings", qa_summary.get("warnings", 0))
    qcol4.metric("N/A", qa_summary.get("not_applicable", 0))

    if qa_summary.get("has_critical_failures"):
        st.error(
            "Critical QA failures detected. "
            "This brief should not be used until failures are resolved."
        )

    qa_results = st.session_state.get("brief_qa_results", [])
    if qa_results:
        with st.expander("View QA check details"):
            _STATUS_ICONS = {"passed": "✓", "failed": "✗", "warning": "⚠", "not_applicable": "—"}
            for r in qa_results:
                icon = _STATUS_ICONS.get(r.get("status", ""), "?")
                color = (
                    "green"
                    if r["status"] == "passed"
                    else "red"
                    if r["status"] == "failed"
                    else "orange"
                    if r["status"] == "warning"
                    else "gray"
                )
                st.markdown(
                    f":{color}[{icon} **{r['check_id']}** {r['check_name']}] — "
                    f"{r.get('details') or r.get('description', '')}"
                )

# ---------------------------------------------------------------------------
# Human review
# ---------------------------------------------------------------------------

st.markdown("---")
st.subheader("Human Review")
st.caption(
    "Record a review action for this brief. "
    "Review labels must not imply clinical validation or approval of the brief for clinical use."
)

current_status = brief.human_review_status
_VALID_NEXT = {
    "not_reviewed": ["in_review"],
    "in_review": ["changes_requested", "approved", "rejected"],
    "changes_requested": ["in_review"],
    "approved": ["in_review"],
    "rejected": ["in_review"],
}

possible_transitions = _VALID_NEXT.get(current_status, [])

if not possible_transitions:
    st.info(f"Current review status: **{current_status}**. No further transitions available.")
else:
    with st.form("review_form"):
        st.caption(f"Current status: **{current_status}**")
        new_status = st.selectbox(
            "New status", options=possible_transitions, key="review_new_status"
        )
        reviewer_label = st.selectbox(
            "Review label",
            options=["Portfolio author review", "Technical review", "Peer review"],
        )
        note = st.text_area("Note (optional)", max_chars=500)
        reviewer_id = st.text_input("Reviewer ID", value="portfolio-author")

        submitted = st.form_submit_button("Submit Review")

    if submitted:
        try:
            from src.review.brief_review_service import BriefReviewService

            review_svc = BriefReviewService()
            record = review_svc.submit_review(
                brief_id=brief.brief_id,
                new_status=new_status,
                reviewer_id=reviewer_id,
                reviewer_label=reviewer_label,
                note=note or None,
            )
            st.success(
                f"Review recorded: {record.previous_status} → {record.new_status} "
                f"({record.reviewer_label})"
            )
            # Reload the brief to reflect new status
            from src.synthesis.brief_service import EvidenceBriefService

            svc = EvidenceBriefService()
            st.session_state["generated_brief"] = svc.get_brief(brief.brief_id)
            st.rerun()
        except Exception as exc:
            st.error(f"Review submission failed: {exc}")

# ---------------------------------------------------------------------------
# Exports
# ---------------------------------------------------------------------------

st.markdown("---")
st.subheader("Export")
st.caption("Download the brief in JSON or Markdown. No PDF or PPTX export is available.")

from src.synthesis.markdown_export import (
    to_citation_map_tsv,
    to_json,
    to_markdown,
    to_provenance_json,
)
from src.synthesis.repository import get_synthesis_repository

export_col1, export_col2, export_col3, export_col4 = st.columns(4)

with export_col1:
    brief_json = to_json(brief)
    st.download_button(
        "Download JSON",
        data=brief_json,
        file_name=f"{brief.brief_id}.json",
        mime="application/json",
    )

with export_col2:
    brief_md = to_markdown(brief)
    st.download_button(
        "Download Markdown",
        data=brief_md,
        file_name=f"{brief.brief_id}.md",
        mime="text/markdown",
    )

with export_col3:
    cit_tsv = to_citation_map_tsv(brief)
    st.download_button(
        "Download Citation Map (TSV)",
        data=cit_tsv,
        file_name=f"{brief.brief_id}_citations.tsv",
        mime="text/tab-separated-values",
    )

with export_col4:
    if brief.provenance:
        prov_json = to_provenance_json(brief.provenance)
        st.download_button(
            "Download Provenance JSON",
            data=prov_json,
            file_name=f"{brief.brief_id}_provenance.json",
            mime="application/json",
        )

# QA report download
try:
    from src.synthesis.markdown_export import to_qa_report_markdown

    repo = get_synthesis_repository()
    qa_results_for_export = repo.get_brief_qa(brief.brief_id)
    if qa_results_for_export:
        qa_md = to_qa_report_markdown(brief.brief_id, qa_results_for_export)
        st.download_button(
            "Download QA Report (Markdown)",
            data=qa_md,
            file_name=f"{brief.brief_id}_qa.md",
            mime="text/markdown",
        )
except Exception:
    pass
