"""Export Center — generate and download all export artifacts for a brief.

Page 7 of the Clinical Question-Evidence Studio.
Gated on: a persisted EvidenceBrief from Page 6.

IMPORTANT: This page does not regenerate brief content.
All exports are derived from the persisted EvidenceBrief and its
associated snapshot, QA results, and review history already in DuckDB.
"""

from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

from app.components.ui_helpers import (
    SESSION_KEY_PHENOTYPE,
    SESSION_KEY_QUESTION,
    SESSION_KEY_RETRIEVAL_RUN,
)

st.set_page_config(
    page_title="Export Center | Clinical Q-E Studio",
    page_icon="📦",
    layout="wide",
)

# ── Safety disclaimer — always visible, always first ──────────────────────────
st.error(
    "**Required notice:** All exported content is generated by automated methods. "
    "It is **not a clinical recommendation**, has not been clinically validated, "
    "and must **not** be used for patient care decisions. "
    "Review status visible in every export does not imply clinical validation."
)

# ── Gate checks ───────────────────────────────────────────────────────────────
question = st.session_state.get(SESSION_KEY_QUESTION)
retrieval_run = st.session_state.get(SESSION_KEY_RETRIEVAL_RUN)
brief_data = st.session_state.get("generated_brief")
brief_id = st.session_state.get("generated_brief_id")

if question is None or st.session_state.get(SESSION_KEY_PHENOTYPE) is None:
    st.warning(
        "Complete Pages 2 and 3 (Question Builder and Phenotype Builder) first.",
        icon="⚠️",
    )
    st.stop()

if retrieval_run is None:
    st.warning("Complete Page 5 (External Evidence) first.", icon="⚠️")
    st.stop()

if brief_data is None or brief_id is None:
    st.warning(
        "No persisted evidence brief found. "
        "Complete Page 6 (Evidence Brief) to generate a brief first.",
        icon="⚠️",
    )
    st.stop()

# ── Load persisted brief ──────────────────────────────────────────────────────
from src.exports.service import ExportGateError, ExportService
from src.schemas.brief import EvidenceBrief, EvidenceSnapshot
from src.schemas.exports import ExportRequest, all_formats
from src.synthesis.repository import get_synthesis_repository

repo = get_synthesis_repository()

brief_dict = repo.get_brief(brief_id)
if brief_dict is None:
    st.error(
        f"Brief `{brief_id}` not found in the database. Return to Page 6 and regenerate the brief."
    )
    st.stop()

brief = EvidenceBrief.model_validate(brief_dict)
snap_raw = repo.get_snapshot(brief.evidence_snapshot_id)
snapshot = EvidenceSnapshot.model_validate(snap_raw) if snap_raw else None
qa_results: list[dict] = repo.get_qa_results(brief_id) or []
review_history: list[dict] = repo.get_review_history(brief_id) or []

export_service = ExportService()

# ── Header ────────────────────────────────────────────────────────────────────
st.title("Export Center")
st.markdown(
    f"**Brief:** `{brief.brief_id}`  ·  "
    f"Version {brief.version}  ·  "
    f"Mode: `{brief.generation_mode}`  ·  "
    f"Review: **{brief.human_review_status}**"
)

# ── Brief metadata cards ──────────────────────────────────────────────────────
m1, m2, m3, m4 = st.columns(4)
m1.metric("Claims", len(brief.claims))
m2.metric(
    "Evidence Records",
    len(snapshot.records) if snapshot else "—",
    help="Records in the immutable evidence snapshot",
)
m3.metric(
    "QA Checks",
    len(qa_results),
    help="BQ-001 through BQ-016",
)
m4.metric(
    "Review Actions",
    len(review_history),
)

st.divider()

# ── Export gate status ────────────────────────────────────────────────────────
gate = export_service.check_export_gate(brief, snapshot, qa_results)

if gate.is_export_blocked:
    st.error(
        "**Export blocked.** The following issues must be resolved before exports can be generated:\n\n"
        + "\n".join(f"- {r}" for r in gate.block_reasons)
    )
    st.stop()

if gate.warnings:
    for w in gate.warnings:
        st.warning(w)

st.success("Export gate: all required checks passed.")

st.divider()

# ── Format selection ──────────────────────────────────────────────────────────
st.subheader("Select Export Formats")

FORMAT_LABELS: dict[str, str] = {
    "json": "Brief JSON",
    "markdown": "Brief Markdown",
    "citation_map_tsv": "Citation Map TSV",
    "citation_map_json": "Citation Map JSON",
    "qa_report_markdown": "QA Report Markdown",
    "qa_report_json": "QA Report JSON",
    "review_history_markdown": "Review History Markdown",
    "review_history_json": "Review History JSON",
    "provenance": "Provenance JSON",
    "schema": "Brief Schema JSON",
    "pdf": "PDF Evidence Brief",
    "pptx": "PowerPoint Summary",
    "zip": "Complete ZIP Bundle",
}

available_fmts = all_formats()
col_l, col_r = st.columns(2)
selected_formats: list[str] = []

with col_l:
    st.markdown("**Text formats**")
    for fmt in [
        "json",
        "markdown",
        "citation_map_tsv",
        "citation_map_json",
        "qa_report_markdown",
        "qa_report_json",
    ]:
        if st.checkbox(FORMAT_LABELS[fmt], value=(fmt in ("json", "markdown")), key=f"fmt_{fmt}"):
            selected_formats.append(fmt)

with col_r:
    st.markdown("**Binary & bundle formats**")
    for fmt in [
        "review_history_markdown",
        "review_history_json",
        "provenance",
        "schema",
        "pdf",
        "pptx",
        "zip",
    ]:
        if st.checkbox(FORMAT_LABELS[fmt], value=(fmt == "zip"), key=f"fmt_{fmt}"):
            selected_formats.append(fmt)

# ── Generate button ───────────────────────────────────────────────────────────
st.divider()

if not selected_formats:
    st.info("Select at least one format above to enable export generation.")
elif st.button("Generate Selected Exports", type="primary", icon="📦"):
    with st.spinner("Generating exports from persisted brief…"):
        req = ExportRequest(brief_id=brief.brief_id, formats=selected_formats)  # type: ignore[arg-type]
        try:
            bundle, artifact_bytes = export_service.generate_bundle(
                request=req,
                brief=brief,
                snapshot=snapshot,
                qa_results=qa_results,
                review_history=review_history,
            )
            st.session_state["last_export_bundle"] = bundle
            st.session_state["last_artifact_bytes"] = artifact_bytes
        except ExportGateError as exc:
            st.error(f"Export blocked: {exc}")
            st.stop()
        except Exception as exc:
            st.error(f"Export generation failed: {exc}")
            st.stop()

    if bundle.errors:
        for err in bundle.errors:
            st.warning(f"Partial error: {err}")

    st.success(
        f"Generated {len(bundle.artifacts_generated)} artifacts. "
        f"Manifest: `{bundle.manifest.manifest_id}`"
    )

# ── Download buttons ──────────────────────────────────────────────────────────
bundle = st.session_state.get("last_export_bundle")
artifact_bytes: dict[str, bytes] = st.session_state.get("last_artifact_bytes", {})

if bundle is not None:
    st.divider()
    st.subheader("Download Artifacts")

    col_info, col_dl = st.columns([2, 1])

    for artifact in bundle.manifest.artifacts:
        content = artifact_bytes.get(artifact.artifact_id)
        if content is None:
            continue
        row_l, row_r = st.columns([3, 1])
        with row_l:
            size_kb = artifact.byte_size / 1024
            st.markdown(
                f"**{FORMAT_LABELS.get(artifact.export_format, artifact.export_format)}**  \n"
                f"`{artifact.filename}` · {size_kb:.1f} KB · "
                f"SHA-256: `{artifact.sha256[:16]}…`"
            )
        with row_r:
            st.download_button(
                label=f"Download {artifact.export_format.upper()}",
                data=content,
                file_name=artifact.filename,
                mime=artifact.mime_type,
                key=f"dl_{artifact.artifact_id}",
            )

    # ZIP download (special key)
    if "zip" in bundle.artifacts_generated and "__zip__" in artifact_bytes:
        st.divider()
        zip_content = artifact_bytes["__zip__"]
        from src.exports.filename import bundle_filename

        zip_fname = bundle.zip_filename or bundle_filename(brief.brief_id, None, brief.version)
        size_mb = len(zip_content) / (1024 * 1024)
        st.info(
            f"ZIP bundle: `{zip_fname}` · {size_mb:.2f} MB  \n"
            f"SHA-256: `{bundle.zip_sha256 or '—'}`  \n"
            f"Manifest: `{bundle.manifest.manifest_id}`"
        )
        st.download_button(
            label="Download Complete ZIP Bundle",
            data=zip_content,
            file_name=zip_fname,
            mime="application/zip",
            key="dl_zip",
            type="primary",
        )

    st.divider()
    st.subheader("Manifest Summary")
    manifest = bundle.manifest
    st.json(
        {
            "manifest_id": manifest.manifest_id,
            "brief_id": manifest.brief_id,
            "brief_version": manifest.brief_version,
            "content_hash": manifest.brief_content_hash,
            "snapshot_hash": manifest.snapshot_hash,
            "review_status": manifest.review_status,
            "origin_classification": manifest.origin_classification,
            "generation_mode": manifest.generation_mode,
            "manifest_sha256": manifest.manifest_sha256,
            "artifact_count": len(manifest.artifacts),
            "total_size_bytes": manifest.total_size_bytes,
            "warnings": manifest.warnings,
        }
    )

# ── Data-origin panel ─────────────────────────────────────────────────────────
st.divider()
with st.expander("Data-Origin Classification", expanded=False):
    st.markdown(f"**Classification:** `{brief.data_origin}`")
    st.markdown(brief.data_notice or "_No data-origin notice recorded._")
    st.markdown(
        """
**Patient-level data:** Entirely synthetic (Synthea FHIR R4). Does not represent real patients.

**External evidence:** Records may be live public-source records, captured public-source fixtures,
or manually constructed demonstration fixtures. The origin classification above reflects the
actual composition of the evidence snapshot for this run.
"""
    )

# ── Footer ────────────────────────────────────────────────────────────────────
st.caption(
    "Clinical Question-Evidence Studio · Export Center · "
    "Educational prototype · Not for clinical use"
)
