"""Pydantic schemas for synthetic cohort construction and attrition reporting.

All cohort data in this application uses SYNTHETIC patient records generated by
Synthea or equivalent tools. No real patient data is used.
"""

from datetime import UTC, date, datetime
from typing import Literal

from pydantic import BaseModel, Field, model_validator


def _utcnow() -> datetime:
    return datetime.now(UTC)


class CohortStep(BaseModel):
    """A single step in the cohort attrition waterfall.

    The invariant records_out == records_in - records_excluded is enforced
    at model validation time to ensure attrition tables reconcile correctly.
    """

    step_number: int = Field(..., ge=1, description="Sequential step index (1-based)")
    label: str = Field(..., description="Short label for attrition visualization (≤60 chars)")
    description: str = Field(..., description="Full description of the criteria applied")
    records_in: int = Field(..., ge=0, description="Patient count entering this step")
    records_excluded: int = Field(..., ge=0, description="Patients excluded by this criterion")
    records_out: int = Field(..., ge=0, description="Patient count passing this step")
    exclusion_reason: str | None = Field(
        None, description="Reason for exclusion (for exclusion steps)"
    )

    @model_validator(mode="after")
    def validate_attrition_math(self) -> "CohortStep":
        """Enforce records_out == records_in - records_excluded."""
        expected = self.records_in - self.records_excluded
        if self.records_out != expected:
            raise ValueError(
                f"Attrition math error in step {self.step_number} ('{self.label}'): "
                f"{self.records_in} in - {self.records_excluded} excluded = {expected} expected, "
                f"but records_out={self.records_out}"
            )
        return self


class DemographicSummary(BaseModel):
    """Demographic characteristics of the final synthetic cohort."""

    total_patients: int = Field(..., ge=0)
    age_mean: float | None = Field(None, ge=0, description="Mean age in years")
    age_std: float | None = Field(None, ge=0, description="Standard deviation of age")
    age_median: float | None = Field(None, ge=0, description="Median age in years")
    age_min: float | None = Field(None, ge=0)
    age_max: float | None = Field(None, ge=0)
    sex_distribution: dict[str, int] = Field(
        default_factory=dict, description="{'male': N, 'female': N, 'other': N}"
    )
    race_distribution: dict[str, int] = Field(
        default_factory=dict, description="Race/ethnicity category -> patient count"
    )


class MissingnessReport(BaseModel):
    """Data completeness summary for a single clinical variable."""

    variable: str = Field(..., description="Variable name (e.g., 'eGFR at baseline')")
    available_count: int = Field(..., ge=0)
    missing_count: int = Field(..., ge=0)
    total_count: int = Field(..., ge=0)
    availability_pct: float = Field(..., ge=0.0, le=100.0)

    @model_validator(mode="after")
    def validate_counts(self) -> "MissingnessReport":
        if self.available_count + self.missing_count != self.total_count:
            raise ValueError(
                f"Missingness count error for '{self.variable}': "
                f"{self.available_count} + {self.missing_count} != {self.total_count}"
            )
        return self


class CohortSummary(BaseModel):
    """Complete summary of a synthetic cohort generation run against a phenotype."""

    id: str = Field(..., description="Unique cohort run identifier")
    phenotype_id: str = Field(..., description="PhenotypeDefinition ID applied")
    phenotype_version: str = Field(..., description="Phenotype version applied")
    run_timestamp: datetime = Field(default_factory=_utcnow)
    initial_population: int = Field(..., ge=0, description="All patients in the source dataset")
    final_cohort_count: int = Field(..., ge=0, description="Patients remaining after all criteria")
    attrition_steps: list[CohortStep] = Field(
        default_factory=list, description="Sequential attrition waterfall"
    )
    demographic_summary: DemographicSummary | None = None
    condition_prevalence: dict[str, float] = Field(
        default_factory=dict,
        description="Condition label -> prevalence (0.0–1.0) in the final cohort",
    )
    medication_exposure: dict[str, int] = Field(
        default_factory=dict,
        description="Medication name -> patient count with ≥1 prescription",
    )
    lab_availability: dict[str, float] = Field(
        default_factory=dict,
        description="Lab test name -> proportion of patients with ≥1 result (0.0–1.0)",
    )
    encounter_summary: dict[str, int] = Field(
        default_factory=dict, description="Encounter type -> total encounter count"
    )
    missingness_report: list[MissingnessReport] = Field(
        default_factory=list, description="Completeness metrics for key analytical variables"
    )
    data_source: str = Field(
        ..., description="Description of synthetic data source (e.g., 'Synthea v3.2, N=1000')"
    )
    is_synthetic: Literal[True] = Field(
        default=True, description="Always True — this application uses only synthetic patient data"
    )
    data_quality_status: Literal["passed", "warning", "failed"] = Field(
        "passed", description="Overall data quality assessment for this run"
    )
    qa_warnings: list[str] = Field(
        default_factory=list, description="Non-critical data quality warnings from this run"
    )


class CohortConfiguration(BaseModel):
    """User-configurable parameters for a single cohort execution run.

    Values here are constrained by the underlying PhenotypeDefinition (e.g. minimum
    lookback) at the service layer; this model only captures the requested values.
    """

    reference_date: date = Field(
        ..., description="Fixed reference/index date for all age and temporal calculations"
    )
    min_age_years: int = Field(18, ge=0, le=120, description="Minimum age at reference date")
    observation_lookback_days: int = Field(
        365, ge=0, description="Required prior observation history in days"
    )
    include_medication_exposure_filter: bool = Field(
        False,
        description=(
            "Apply the OPTIONAL exploratory SGLT2 exposure filter. This filter uses "
            "candidate, LLM-suggested, unverified RxNorm mappings and never produces a "
            "required inclusion step."
        ),
    )
    medication_lookback_days: int = Field(
        180, ge=0, description="Window for the optional medication exposure filter"
    )
    require_lab_availability: bool = Field(
        False, description="If True, require at least one qualifying lab result in window"
    )
    lab_lookback_days: int = Field(365, ge=0, description="Window for the optional lab filter")
    dataset_id: str = Field(..., description="Synthetic FHIR dataset identifier to run against")


class CohortAttrition(BaseModel):
    """Sequential attrition waterfall for a single cohort run."""

    steps: list[CohortStep] = Field(default_factory=list)

    @property
    def reconciles(self) -> bool:
        """True if every step's records_out matches the next step's records_in."""
        for current, nxt in zip(self.steps, self.steps[1:], strict=False):
            if current.records_out != nxt.records_in:
                return False
        return True

    @property
    def final_count(self) -> int:
        return self.steps[-1].records_out if self.steps else 0


class ExclusionSummary(BaseModel):
    """Aggregated exclusion-reason counts across an entire cohort run."""

    reason: str
    excluded_count: int = Field(..., ge=0)
    step_id: str


class CohortProvenance(BaseModel):
    """Provenance metadata for a single cohort execution run."""

    run_id: str
    phenotype_id: str
    phenotype_version: str
    phenotype_review_status: Literal["draft", "under_review", "approved"]
    dataset_id: str
    fhir_ingestion_run_id: str
    configuration_hash: str = Field(..., description="Deterministic hash of CohortConfiguration")
    timestamp: datetime = Field(default_factory=_utcnow)
    is_synthetic: Literal[True] = True


class CohortRun(BaseModel):
    """Complete persisted record of a single cohort execution."""

    run_id: str
    configuration: CohortConfiguration
    attrition: CohortAttrition
    summary: CohortSummary
    provenance: CohortProvenance
    qa_status: Literal["passed", "warning", "failed"] = "passed"
    warnings: list[str] = Field(default_factory=list)
