"""Secure ZIP bundle creation for export artifacts.

Security properties:
- No archive entry begins with /, \\, ../, or ..\\
- No absolute local paths in entries
- Filenames are sanitized before inclusion
- Temporary directory is cleaned up after completion
- No secrets, env files, or Python cache files are included
"""

from __future__ import annotations

import io
import zipfile

from src.exports.checksums import sha256_bytes
from src.exports.filename import assert_no_traversal, sanitize_filename
from src.exports.manifest import manifest_to_bytes
from src.schemas.exports import ExportArtifact, ExportManifest

# ZIP entries that are never allowed, regardless of how they're named
_BLOCKED_NAMES = {
    ".env",
    ".env.local",
    ".env.production",
    "id_rsa",
    "id_ed25519",
    ".DS_Store",
    "Thumbs.db",
}

_BLOCKED_EXTENSIONS = {".pyc", ".pyo", ".pyd"}
_BLOCKED_DIRS = {"__pycache__", ".git", ".venv", "node_modules"}


def _is_blocked(name: str) -> bool:
    base = name.lstrip("/\\").split("/")[-1].split("\\")[-1]
    if base in _BLOCKED_NAMES:
        return True
    if any(base.endswith(ext) for ext in _BLOCKED_EXTENSIONS):
        return True
    if any(part in _BLOCKED_DIRS for part in name.replace("\\", "/").split("/")):
        return True
    return False


_README_TEMPLATE = """\
Evidence Brief Export Bundle
============================

This archive was generated by the Clinical Question-Evidence Studio.

DISCLAIMER
----------
{disclaimer}

Contents
--------
brief/       Structured evidence brief (JSON, Markdown, PDF, PPTX)
evidence/    Citation map and evidence snapshot
qa/          QA report
review/      Human review history
provenance/  Provenance JSON
schemas/     JSON Schema definitions
manifest.json  Complete artifact manifest with checksums

Data Origin
-----------
{data_notice}

Review Status at Export Time
----------------------------
{review_status}

This is an educational portfolio prototype. It has not been clinically
validated and does not provide medical advice.
"""

_SUBFOLDER_MAP: dict[str, str] = {
    "json": "brief",
    "markdown": "brief",
    "pdf": "brief",
    "pptx": "brief",
    "citation_map_tsv": "evidence",
    "citation_map_json": "evidence",
    "qa_report_markdown": "qa",
    "qa_report_json": "qa",
    "review_history_markdown": "review",
    "review_history_json": "review",
    "provenance": "provenance",
    "schema": "schemas",
}


def build_zip(
    manifest: ExportManifest,
    artifact_contents: dict[str, bytes],
    disclaimer: str,
    data_notice: str,
    review_status: str,
) -> bytes:
    """Assemble all artifacts into a ZIP archive and return raw bytes.

    Args:
        manifest: Complete export manifest.
        artifact_contents: Maps artifact_id → raw bytes.
        disclaimer: Required disclaimer text for README.
        data_notice: Data-origin notice for README.
        review_status: Human review status at export time.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        # manifest.json at root
        manifest_bytes = manifest_to_bytes(manifest)
        zf.writestr("manifest.json", manifest_bytes)

        # README.txt at root
        readme = _README_TEMPLATE.format(
            disclaimer=disclaimer,
            data_notice=data_notice,
            review_status=review_status,
        )
        zf.writestr("README.txt", readme.encode("utf-8"))

        # Artifacts by subfolder
        for artifact in manifest.artifacts:
            content = artifact_contents.get(artifact.artifact_id)
            if content is None:
                continue

            subfolder = _SUBFOLDER_MAP.get(artifact.export_format, "misc")
            safe_name = sanitize_filename(artifact.filename)
            entry_path = f"{subfolder}/{safe_name}"

            # Security: block traversal and absolute paths
            assert_no_traversal(entry_path)
            if _is_blocked(safe_name):
                continue

            zf.writestr(entry_path, content)

    return buf.getvalue()


def verify_zip(zip_bytes: bytes) -> tuple[bool, list[str]]:
    """Verify that a ZIP archive contains no traversal entries and passes structural checks.

    Returns (ok, list_of_violations).
    """
    violations: list[str] = []
    try:
        with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
            for entry in zf.infolist():
                name = entry.filename
                try:
                    assert_no_traversal(name)
                except ValueError as exc:
                    violations.append(str(exc))
                if _is_blocked(name):
                    violations.append(f"Blocked file included in archive: {name!r}")
    except zipfile.BadZipFile as exc:
        violations.append(f"Bad ZIP file: {exc}")
    return len(violations) == 0, violations


def zip_artifact(artifact: ExportArtifact, content: bytes) -> tuple[str, bytes]:
    """Return (checksum, zip_bytes) wrapping a single artifact for streaming."""
    data = build_zip(
        manifest=ExportManifest(
            manifest_id=artifact.artifact_id,
            brief_id=artifact.brief_id,
            brief_version=artifact.brief_version,
            brief_content_hash="",
            snapshot_hash="",
            bundle_name=artifact.filename,
            generation_mode="",
            origin_classification=artifact.origin_classification,
            review_status=artifact.review_status,
            artifacts=[artifact],
        ),
        artifact_contents={artifact.artifact_id: content},
        disclaimer="",
        data_notice="",
        review_status=artifact.review_status,
    )
    return sha256_bytes(data), data
